import { ScrollView } from "std-widgets.slint";
import { ScriptModule } from "script_module.slint";


export component ScriptsList {

    callback handle_script_module_click(name: string, description: string);
    callback handle_script_execution();


    property <[{name: string, description: string}]> scripts: [
        { name: "Limpeza de Arquivos Temporários", description: "Remova arquivos temporários e\nlibere espaço no seu sistema." },
        { name: "Correção de erros de internet", description: "Mantenha seus drivers atualizados para\nmelhor desempenho e estabilidade." },
        { name: "Atualização de Drivers", description: "Mantenha seus drivers atualizados para\nmelhor desempenho e estabilidade." },
        { name: "Atualização de Drivers", description: "Mantenha seus drivers atualizados para\nmelhor desempenho e estabilidade." },
        {name: "Test", description: "Test description"}
    ];
    
    VerticalLayout {
        padding-left: 24px;

        ScrollView {
            width: root.width;
            height: root.height;
            viewport-width: self.width;
            viewport-height: 300px;
    
    
    
            GridLayout {
                width: parent.width;  
                spacing: 16px;
    
                for module[i] in scripts : ScriptModule {
                    row: Math.floor(i / 2);
                    col: Math.mod(i, 2);
                    width: (root.width - 16px) / 2;
                    script_name: module.name;
                    script_description: module.description;

                    handle_script_module_click => {
                        root.handle_script_module_click(module.name, module.description);
                    }

                    handle_script_execution => {
                        root.handle_script_execution();
                    }
                }
            }
    }
    }
    
}