export component ScriptDetails {
    


    in-out property <{name: string, description: string}> selected_script;

    Rectangle {

        background: #0053d8;
        border-radius: 8px;

        VerticalLayout {
            padding-left: 24px;
            padding-top: 24px;
    
            Text { text: root.selected_script.name; font-size: 28px; font-weight: 700; color: #F8FAFC; }
            Text { text: root.selected_script.description; font-size: 18px; font-weight: 400; color: #94A3B8; }
        }
    }

    
}