import { ScrollView } from "std-widgets.slint";
import { ScriptModule } from "script_module.slint";


export component ScriptsList {

    callback handle_script_module_select(string, string, string, image);
    callback handle_script_execution();

    property <[{ name: string, description: string, description_long: string, img_url: image}]> scripts: [
        {
            name: "Limpeza de Arquivos Temporários",
            description: "Remova arquivos temporários e\nlibere espaço no seu sistema.",
            description_long: "Libere espaço no seu sistema removendo arquivos\ntemporários, cache e outros arquivos desnecessários.",
            img_url: @image-url("../../public/images/folder-icon.png")
        },
        {
            name: "Correção de erros de internet",
            description: "Corrigir erros básicos\nde conexão.",
            description_long: "Corrija erros básicos de conexão com scripts para \nreset de conexão limpeza de cache DNS etc.",
            img_url: @image-url("../../public/images/internet-sign.png")
        },
    ];

    VerticalLayout {
        padding-left: 25px;

        ScrollView {
            width: root.width;
            height: root.height;
            viewport-width: self.width;
            viewport-height: 300px;

            GridLayout {
                width: parent.width;
                spacing: 16px;

                for module[i] in scripts: ScriptModule {
                    row: Math.floor(i / 2);
                    col: Math.mod(i, 2);
                    width: (root.width - 16px) / 2;
                    script_name: module.name;
                    script_description: module.description;
                    img_url: module.img_url;

                    handle_script_module_click => {
                        root.handle_script_module_select(module.name, module.description, module.description_long, module.img_url);
                    }

                    handle_script_execution => {
                        root.handle_script_execution();
                    }
                }
            }
        }
    }
}
