
import {WelcomePageStats } from "./WelcomeWindow/welcome_page_stats.slint";
import { WelcomePage2 } from "./WelcomeWindow/welcome_page2.slint";

export component MainWindow inherits Window {
    width: 1100px;
    height: 720px;
    background: #0F172A;
    title: "fixIT - Dashboard";

    in-out property <string> current_page: "welcome";

    in-out property <int> memory_usage: 0;
    in-out property <int> cpu_usage: 0;
    in-out property <int> disk_usage: 0;
    in-out property <bool> is_connected: false;

    if (root.current_page == "welcome") : WelcomePage2 {
        width: parent.width;
        height: parent.height;

        cpu_usage: root.cpu_usage;
        memory_usage: root.memory_usage;
        disk_usage: root.disk_usage;
        is_connected: root.is_connected;
    }


}