import { WelcomeWindowModule } from "./welcome_window_module.slint";

export component ModulesList {
    callback navigate_to(string);

    GridLayout {

        width: parent.width;
        spacing: 20px;

        Row {

            WelcomeWindowModule {
                width: 50%; // Width is set on all modules to keep them with the same size
                module_title: "Monitoramento";
                module_name: "monitoring";
                module_description: "Acompanhe as estatística do seu sistema.";
                navigate_to(page) => {
                    root.navigate_to(page);
                }
            }

            WelcomeWindowModule {
                width: 50%;
                module_title: "Suporte Técnico";
                module_name: "support";
                module_description: "Resolva problemas técnicos simples com poucos cliques.";
                navigate_to(page) => {
                    root.navigate_to(page);
                }
            }
        }

        Row {
            // TODO: Create this component and then uncomment it
            // WelcomeWindowModule {
            //     module_title: "Atualizações";
            //     module_name: "updates";
            //     module_description: "Mantenha seu sistema atualizado com os últimos patches de segurança.";
            //     navigate_to(page) => { root.navigate_to(page); }
            // }

            // TODO: Create this component and then uncomment it
            // WelcomeWindowModule {
            //     module_title: "Configurações";
            //     module_name: "settings";
            //     module_description: "Personalize as preferências do aplicativo e do sistema.";
            //     navigate_to(page) => { root.navigate_to(page); }
            // }

        }
    }
}
