export component StoragePercentage {

    width: 200px;
    height: 220px;

    in property <int> disk_usage_percentage;

    Rectangle {

        background: #1E293B;
        border-radius: 12px;
        border-width: 1px;
        border-color: #334155;
        
        drop-shadow-color: #00000040;
        drop-shadow-blur: 8px;
        drop-shadow-offset-y: 4px;


        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                    alignment: center;


                Rectangle {
                    width: 110px;
                    height: 140px;
                    border-color: white;
                    border-width: 2px;     
                    
                    VerticalLayout {
                        alignment: end;
                        spacing: 0px;
                        padding: 2px;
                            
                        Rectangle {
                            width: parent.width * 0.9689;
                            height: parent.height * (root.disk_usage_percentage / 100);
                            background: #3B82F6;
                        }
                    }
                        
                }
            }

            HorizontalLayout {
                padding-top: 10px;
                spacing: 1px;
                alignment: center;

                Text {
                    text: root.disk_usage_percentage + "%";
                    font-size: 14px;
                    font-weight: 700;
                    color: #F8FAFC;
                }

                Text {
                    text: "usado";
                    font-size: 14px;
                    color: #94A3B8;
                    font-weight: 600;
                }
            }

        }
    }
    
}