import {PagesHeader} from "../components/shared/pages_header.slint";
import { FeaturesList } from "../components/monitoring_page/features_list.slint";

export component MonitoringPage {


    in property <int> disk_usage;
    callback navigate_to(string);


    VerticalLayout {

        PagesHeader {
            header_text: "Monitoramento do Sistema";
            navigate_to(page) => {
                root.navigate_to(page);
            }
        }

        FeaturesList {
            width: parent.width;
            disk_usage: root.disk_usage;
        }

    }
}
