import { ScriptsList } from "../components/support_page/scripts_list.slint";
export component SupportPage {
    
    // Temp properties for testing
    // TO-DO: Change to parent.width and parent.height
    width: 1100px;
    height: 720px;

    in-out property <{name: string, description: string}> selected_script;


    VerticalLayout {

        HorizontalLayout {
        height: parent.height * 0.15;
        alignment: center;
        padding-top: 24px;
        padding-bottom: 24px;

        Text { text: "Suporte Técnico"; font-size: 28px; font-weight: 700; color: #F8FAFC; }
        }

        ScriptsList {
            height: parent.height * 0.3;
            width: parent.width * 0.85;
            
        }

    }
    
}