export component SupportPage {
    
    // Temp properties for testing
    // TO-DO: Change to parent.width and parent.height
    width: 1100px;
    height: 720px;


    VerticalLayout {

        HorizontalLayout {
        alignment: center;
        padding-top: 24px;
        padding-bottom: 24px;

        Text { text: "Como posso ajudar hoje?"; font-size: 28px; font-weight: 700; color: #F8FAFC; }
        }

    }
    
}