import { PagesHeader } from "../components/shared/pages_header.slint";
import {
    WelcomePageStats,
} from "../components/welcome_page/welcome_page_stats.slint";
import { ModulesList } from "../components/welcome_page/modules_list.slint";


export component WelcomePage {

    // TO-DO: Refactor code to use global AppState properties instead of local ones
    // When slint fix the global
    in-out property <int> memory_usage: 0;
    in-out property <int> cpu_usage: 0;
    in-out property <int> disk_usage: 0;
    in-out property <bool> is_connected: false;

    // Callback function passed down to module list and then to each module
    callback navigate_to(string);

    VerticalLayout {
        spacing: 32px;
        padding-top: 40px;
        alignment: start;

        PagesHeader {
            header_text: "Bem-vindo ao fixIT";
        }

        HorizontalLayout {
            alignment: center;
            WelcomePageStats {
                width: parent.width * 0.90;
                cpu_usage: root.cpu_usage;
                memory_usage: root.memory_usage;
                disk_usage: root.disk_usage;
                is_connected: root.is_connected;
            }
        }

        VerticalLayout {
            padding-left: 40px;
            padding-right: 40px;
            spacing: 16px;
            Text {
                text: "O que deseja utilizar?";
                font-size: 24px;
                color: #ffffff;
                font-weight: 600;
            }

            Rectangle {
                width: parent.width - 80px;
                height: 2px;
                background: #334155;

                drop-shadow-color: #00000040;
                drop-shadow-blur: 8px;
                drop-shadow-offset-y: 4px;
            }

            ModulesList {
                width: parent.width - 80px;
                navigate_to(page) => {
                    root.navigate_to(page);
                }
            }
        }
    }
}
